_format_version: "1.1"

plugins:
  - name: safeline
    config:
      host: safeline-detector
      port: 8000
  - name: cors
    config:
      origins: ["*"]
      methods: ["GET","POST","PUT","DELETE","OPTIONS"]
      headers: ["Authorization","Content-Type","X-Requested-With"]
      credentials: true
      max_age: 3600

services:
  - name: kong-admin
    url: http://kong:8001
    plugins:
    routes:
      - name: kong-admin-route
        protocols: ["http","https"]
        paths: ["/kong-admin"]
        strip_path: false
        preserve_host: true

  - name: widgetbook
    url: http://widgetbook:80
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE","OPTIONS"]
          headers: ["Authorization","Content-Type","X-Requested-With"]
          credentials: true
          max_age: 3600
    routes:
      - name: widgetbook-route
        protocols: ["http","https"]
        paths: ["/widgetbook"]
        strip_path: false
        preserve_host: true

  - name: webapp
    url: http://webapp:80
    plugins:
    routes:
      - name: webapp-route
        protocols: ["http","https"]
        paths: ["/app"]
        strip_path: false
        preserve_host: true

  - name: keycloak
    url: http://keycloak:8080
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE","OPTIONS"]
          headers: ["Authorization","Content-Type","X-Requested-With"]
          credentials: true
          max_age: 3600
    routes:
      - name: keycloak-route
        protocols: ["http","https"]
        paths: ["/auth"]
        strip_path: false
        preserve_host: true

  - name: temporal-ui
    url: http://temporal-ui:8080
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE","OPTIONS"]
          headers: ["Authorization","Content-Type","X-Requested-With"]
          credentials: true
          max_age: 3600
    routes:
      - name: temporal-ui-route
        protocols: ["http","https"]
        paths: ["/temporal"]
        strip_path: false
        preserve_host: true

  - name: safeline-dashboard
    url: https://safeline-mgt:1443
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE","OPTIONS"]
          headers: ["Authorization","Content-Type","X-Requested-With"]
          credentials: true
          max_age: 3600
    routes:
      - name: safeline-dashboard-route
        protocols: ["https"]
        paths: ["/safeline"]
        strip_path: false
        preserve_host: true

  - name: website
    url: http://website:80
    plugins:
    routes:
      - name: website-route
        protocols: ["http","https"]
        paths: ["/"]
        strip_path: false
        preserve_host: true

  - name: grafana
    url: http://grafana:3000
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE","OPTIONS"]
          headers: ["Authorization","Content-Type","X-Requested-With"]
          credentials: true
          max_age: 3600
    routes:
      - name: grafana-route
        protocols: ["http","https"]
        paths: ["/grafana"]
        strip_path: false
        preserve_host: true

  - name: customer_service-grpc
    url: grpc://customer_service:50051
    plugins:
      - name: request-transformer
        config:
          add:
            headers: ["Authorization:${headers.authorization}"]
      - name: oauth2
        config:
          enable_authorization_code: true
          enable_client_credentials: true
          enable_password_grant: false
          global_credentials: false
          token_expiration: 7200
          scopes: ["read", "write"]
          mandatory_scope: false
          hide_credentials: false
          enable_implicit_grant: false
          accept_http_if_already_terminated: true
          reuse_refresh_token: true
          auth_header_name: "Authorization"
          refresh_token_ttl: 1209600
          provision_key: "your-provision-key"
    routes:
      - name: customer_service-route
        protocols: ["grpc"]
        paths: ["/grpc/customer_service"]
        strip_path: false

  - name: customer-get
    url: grpc://customer_service:50051
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/customer.proto
      - name: request-transformer
        config:
          add:
            headers: ["Authorization:${headers.authorization}"]
      - name: oauth2
        config:
          enable_authorization_code: true
          enable_client_credentials: true
          enable_password_grant: false
          global_credentials: false
          token_expiration: 7200
          scopes: ["read", "write"]
          mandatory_scope: false
          hide_credentials: false
          enable_implicit_grant: false
          accept_http_if_already_terminated: true
          reuse_refresh_token: true
          auth_header_name: "Authorization"
          refresh_token_ttl: 1209600
          provision_key: "your-provision-key"
    routes:
      - name: customer-get-route
        protocols: ["http", "https"]
        paths: ["/api/v1/customer"]
        methods: ["GET"]
        strip_path: false

  - name: customer-add
    url: grpc://customer_service:50051
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/customer.proto
      - name: request-transformer
        config:
          add:
            headers: ["Authorization:${headers.authorization}"]
      - name: oauth2
        config:
          enable_authorization_code: true
          enable_client_credentials: true
          enable_password_grant: false
          global_credentials: false
          token_expiration: 7200
          scopes: ["read", "write"]
          mandatory_scope: false
          hide_credentials: false
          enable_implicit_grant: false
          accept_http_if_already_terminated: true
          reuse_refresh_token: true
          auth_header_name: "Authorization"
          refresh_token_ttl: 1209600
          provision_key: "your-provision-key"
    routes:
      - name: customer-add-route
        protocols: ["http", "https"]
        paths: ["/api/v1/customer"]
        methods: ["PUT"]
        strip_path: false

  - name: customer-update
    url: grpc://customer_service:50051
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/customer.proto
      - name: request-transformer
        config:
          add:
            headers: ["Authorization:${headers.authorization}"]
      - name: oauth2
        config:
          enable_authorization_code: true
          enable_client_credentials: true
          enable_password_grant: false
          global_credentials: false
          token_expiration: 7200
          scopes: ["read", "write"]
          mandatory_scope: false
          hide_credentials: false
          enable_implicit_grant: false
          accept_http_if_already_terminated: true
          reuse_refresh_token: true
          auth_header_name: "Authorization"
          refresh_token_ttl: 1209600
          provision_key: "your-provision-key"
    routes:
      - name: customer-update-route
        protocols: ["http", "https"]
        paths: ["/api/v1/customer"]
        methods: ["POST"]
        strip_path: false

  - name: customer-list
    url: grpc://customer_service:50051
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/customer.proto
      - name: request-transformer
        config:
          add:
            headers: ["Authorization:${headers.authorization}"]
      - name: oauth2
        config:
          enable_authorization_code: true
          enable_client_credentials: true
          enable_password_grant: false
          global_credentials: false
          token_expiration: 7200
          scopes: ["read", "write"]
          mandatory_scope: false
          hide_credentials: false
          enable_implicit_grant: false
          accept_http_if_already_terminated: true
          reuse_refresh_token: true
          auth_header_name: "Authorization"
          refresh_token_ttl: 1209600
          provision_key: "your-provision-key"
    routes:
      - name: customer-list-route
        protocols: ["http", "https"]
        paths: ["/api/v1/customers"]
        methods: ["GET"]
        strip_path: false


consumers:
  - username: api-client
    custom_id: api-client-1
    oauth2_credentials:
    - name: "API Client"
      client_id: "client-id"
      client_secret: "client-secret"
      redirect_uris: ["http://localhost:80/callback"]
      hash_secret: false
