services:
  # Observability
  elasticsearch:
    container_name: saaster-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    networks:
      - saaster-network
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data

  # Orchestration
  temporal-postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_DB: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - temporal-postgresql
      - elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_DB=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/docker.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - saaster-network
      - temporal-network
    expose:
      - 7233
    ports:
      - "7233:7233"
    volumes:
      - ./backend/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - saaster-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - saaster-network
    ports:
      - "8081:8080"


  # IAM
  postgres:
    image: postgres:15.6
    container_name: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm --verbose
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - saaster-network
      - keycloak-network

  # User Manager Microservice
  user_db:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_manager
      POSTGRES_PASSWORD: password
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - saaster-network
      - user-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_manager -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_manager:
    build:
      context: ./backend/user_manager
      dockerfile: Dockerfile
    container_name: user_manager
    depends_on:
      user_db:
        condition: service_healthy
      temporal:
        condition: service_started
    environment:
      - SERVER_PORT=8080
      - DB_HOST=user_db
      - DB_PORT=5432
      - DB_USER=user_manager
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=user-manager-task-queue
      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - saaster-network
      - user-network
    ports:
      - "8082:8080"

  user_manager_dapr:
    image: daprio/daprd:1.12.0
    container_name: user_manager_dapr
    depends_on:
      - user_manager
    command: [
      "./daprd",
      "--app-id", "user-manager",
      "--app-port", "8080",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--components-path", "/components",
      "--config", "/config/config.yaml"
    ]
    volumes:
      - ./backend/user_manager/deployments/dapr/components:/components
      - ./backend/user_manager/deployments/dapr:/config
    network_mode: "service:user_manager"

networks:
  saaster-network:
    driver: bridge
    name: saaster-network
  temporal-network:
    driver: bridge
    name: temporal-network
  keycloak-network:
    driver: bridge
    name: keycloak-network
  user-network:
    driver: bridge
    name: user-network

volumes:
  postgres_data:
  user_db_data:
