apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch-logs
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: "http://saaster-elasticsearch:9200/client-manager-logs/_doc"
    - name: method
      value: "POST"
