http:
  middlewares:
    kong-waf:
      plugin:
        moduleName: github.com/traefik/modsecurity-plugin
        version: v0.1.0
        type: middleware
        config:
          connector:
            secRuleEngine: DetectionOnly
            requestBodyAccess: On
            responseBodyAccess: On
            secRules:
              - SecRuleEngine On
              - SecRequestBodyAccess On
              - SecResponseBodyAccess On
              - SecRule REQUEST_HEADERS:Content-Type "(?:application(?:/soap\+|/)|text/)xml" "id:1000,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"
              - SecRule REQUEST_HEADERS:Content-Type "application/json" "id:1001,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"
              - SecRule ARGS_NAMES|ARGS|XML:/* "@rx (?i)([<>;]|javascript:|vbscript:|expression:|url\s*\(|document\.|alert\s*\(|eval\s*\()" "id:1002,phase:2,t:none,block,msg:'XSS Attack'"
              - SecRule ARGS_NAMES|ARGS|REQUEST_BODY "@rx (?i)(select|union|insert|update|delete|drop|alter)\s+.*\s+(from|into|where)" "id:1003,phase:2,t:none,block,msg:'SQL Injection'"
