import 'package:flutter/material.dart';

import '../atoms/colors.dart';
import '../organisms/app_bar.dart';
import '../organisms/navigation.dart';

/// Design System Application Scaffold
class DSAppScaffold {
  // Private constructor to prevent instantiation
  DSAppScaffold._();

  /// Standard application scaffold
  static Widget standard({
    required BuildContext context,
    required Widget body,
    String? title,
    Widget? appBarTitle,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double appBarElevation = 0,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
    bool primary = true,
  }) {
    return Scaffold(
      appBar:
          title != null || appBarTitle != null
              ? DSAppBars.appStandardAppBar(
                context: context,
                title: title ?? '',
                actions: appBarActions,
                leading: leading,
                centerTitle: centerTitle,
                backgroundColor: appBarBackgroundColor,
                foregroundColor: appBarForegroundColor,
                elevation: appBarElevation,
                bottom: bottom,
              )
              : null,
      body: body,
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
      primary: primary,
    );
  }

  /// Application scaffold with bottom navigation
  static Widget withBottomNavigation({
    required BuildContext context,
    required Widget body,
    required List<BottomNavigationItem> items,
    required int currentIndex,
    required ValueChanged<int> onTap,
    String? title,
    Widget? appBarTitle,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double appBarElevation = 0,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Color? bottomNavBackgroundColor,
    Color? bottomNavSelectedItemColor,
    Color? bottomNavUnselectedItemColor,
    double bottomNavElevation = 8,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
  }) {
    return Scaffold(
      appBar:
          title != null || appBarTitle != null
              ? DSAppBars.appStandardAppBar(
                context: context,
                title: title ?? '',
                actions: appBarActions,
                leading: leading,
                centerTitle: centerTitle,
                backgroundColor: appBarBackgroundColor,
                foregroundColor: appBarForegroundColor,
                elevation: appBarElevation,
                bottom: bottom,
              )
              : null,
      body: body,
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: DSNavigation.appBottomNavBar(
        context: context,
        items: items,
        currentIndex: currentIndex,
        onTap: onTap,
        backgroundColor: bottomNavBackgroundColor,
        selectedItemColor: bottomNavSelectedItemColor,
        unselectedItemColor: bottomNavUnselectedItemColor,
        elevation: bottomNavElevation,
      ),
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }

  /// Application scaffold with drawer navigation
  static Widget withDrawer({
    required BuildContext context,
    required Widget body,
    required List<DrawerItem> drawerItems,
    required String drawerHeaderTitle,
    String? title,
    Widget? appBarTitle,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double appBarElevation = 0,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    String? drawerHeaderSubtitle,
    Widget? drawerHeaderLeading,
    Widget? drawerHeaderTrailing,
    Color? drawerBackgroundColor,
    double drawerWidth = 304,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
  }) {
    return Scaffold(
      appBar:
          title != null || appBarTitle != null
              ? DSAppBars.appStandardAppBar(
                context: context,
                title: title ?? '',
                actions: appBarActions,
                leading: leading,
                centerTitle: centerTitle,
                backgroundColor: appBarBackgroundColor,
                foregroundColor: appBarForegroundColor,
                elevation: appBarElevation,
                bottom: bottom,
              )
              : null,
      body: body,
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: DSNavigation.appDrawer(
        context: context,
        items: drawerItems,
        headerTitle: drawerHeaderTitle,
        headerSubtitle: drawerHeaderSubtitle,
        headerLeading: drawerHeaderLeading,
        headerTrailing: drawerHeaderTrailing,
        backgroundColor: drawerBackgroundColor,
        width: drawerWidth,
      ),
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }

  /// Responsive application scaffold
  static Widget responsive({
    required BuildContext context,
    required Widget body,
    required List<NavigationItem> navigationItems,
    required int selectedIndex,
    required ValueChanged<int> onNavigationItemSelected,
    String? title,
    Widget? appBarTitle,
    List<Widget>? appBarActions,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    bool extendedRail = false,
    Widget? railLeading,
    Widget? railTrailing,
    Widget? bottomNavBarTrailing,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
  }) {
    return DSNavigation.appResponsiveNavigation(
      context: context,
      items: navigationItems,
      selectedIndex: selectedIndex,
      onItemSelected: onNavigationItemSelected,
      body: body,
      appTitle: title,
      appLogo: appBarTitle,
      appBarActions: appBarActions,
      floatingActionButton: floatingActionButton,
      extendedRail: extendedRail,
      railLeading: railLeading,
      railTrailing: railTrailing,
      bottomNavBarTrailing: bottomNavBarTrailing,
    );
  }

  /// Application scaffold with tabbed navigation
  static Widget withTabs({
    required BuildContext context,
    required List<String> tabs,
    required TabController tabController,
    required List<Widget> tabViews,
    String? title,
    Widget? appBarTitle,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double appBarElevation = 0,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
    bool isScrollable = false,
    Color? tabLabelColor,
    Color? tabUnselectedLabelColor,
    Color? tabIndicatorColor,
    double tabIndicatorWeight = 2,
    TabBarIndicatorSize tabIndicatorSize = TabBarIndicatorSize.tab,
    EdgeInsets? tabPadding,
    EdgeInsets? tabLabelPadding,
  }) {
    return Scaffold(
      appBar: AppBar(
        title: appBarTitle ?? (title != null ? Text(title) : null),
        actions: appBarActions,
        leading: leading,
        centerTitle: centerTitle,
        backgroundColor: appBarBackgroundColor ?? DSColors.primaryApp,
        surfaceTintColor: appBarBackgroundColor ?? DSColors.primaryApp,
        foregroundColor: appBarForegroundColor ?? DSColors.textOnPrimary,
        elevation: appBarElevation,
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(48),
          child: DSNavigation.appTabBar(
            context: context,
            tabs: tabs,
            tabController: tabController,
            isScrollable: isScrollable,
            labelColor: tabLabelColor,
            unselectedLabelColor: tabUnselectedLabelColor,
            indicatorColor: tabIndicatorColor,
            indicatorWeight: tabIndicatorWeight,
            indicatorSize: tabIndicatorSize,
            padding: tabPadding,
            labelPadding: tabLabelPadding,
          ),
        ),
      ),
      body: TabBarView(controller: tabController, children: tabViews),
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }

  /// Application scaffold with sliver app bar
  static Widget withSliverAppBar({
    required BuildContext context,
    required String title,
    required List<Widget> slivers,
    String? subtitle,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double expandedHeight = 200,
    Widget? flexibleSpace,
    bool pinned = true,
    bool floating = false,
    bool snap = false,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
  }) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          DSAppBars.appSliverAppBar(
            context: context,
            title: title,
            subtitle: subtitle,
            actions: appBarActions,
            leading: leading,
            centerTitle: centerTitle,
            backgroundColor: appBarBackgroundColor,
            foregroundColor: appBarForegroundColor,
            expandedHeight: expandedHeight,
            flexibleSpace: flexibleSpace,
            pinned: pinned,
            floating: floating,
            snap: snap,
            bottom: bottom,
          ),
          ...slivers,
        ],
      ),
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }

  /// Application scaffold with search app bar
  static Widget withSearchAppBar({
    required BuildContext context,
    required Widget body,
    required TextEditingController searchController,
    required ValueChanged<String> onSubmitted,
    ValueChanged<String>? onChanged,
    VoidCallback? onClear,
    String hintText = 'Search',
    List<Widget>? appBarActions,
    Widget? leading,
    Color? backgroundColor,
    Color? appBarBackgroundColor,
    Color? appBarForegroundColor,
    double appBarElevation = 0,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = false,
    bool resizeToAvoidBottomInset = true,
  }) {
    return Scaffold(
      appBar: DSAppBars.appSearchAppBar(
        context: context,
        searchController: searchController,
        onSubmitted: onSubmitted,
        onChanged: onChanged,
        onClear: onClear,
        hintText: hintText,
        actions: appBarActions,
        leading: leading,
        backgroundColor: appBarBackgroundColor,
        foregroundColor: appBarForegroundColor,
        elevation: appBarElevation,
        bottom: bottom,
      ),
      body: body,
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }

  /// Application scaffold with transparent app bar
  static Widget withTransparentAppBar({
    required BuildContext context,
    required Widget body,
    String? title,
    List<Widget>? appBarActions,
    Widget? leading,
    bool centerTitle = false,
    Color? backgroundColor,
    Color? appBarForegroundColor,
    PreferredSizeWidget? bottom,
    Widget? floatingActionButton,
    FloatingActionButtonLocation? floatingActionButtonLocation,
    Widget? bottomNavigationBar,
    Widget? drawer,
    Widget? endDrawer,
    bool extendBody = false,
    bool extendBodyBehindAppBar = true,
    bool resizeToAvoidBottomInset = true,
  }) {
    return Scaffold(
      extendBodyBehindAppBar: extendBodyBehindAppBar,
      appBar: DSAppBars.appTransparentAppBar(
        context: context,
        title: title,
        actions: appBarActions,
        leading: leading,
        centerTitle: centerTitle,
        foregroundColor: appBarForegroundColor,
        bottom: bottom,
      ),
      body: body,
      backgroundColor: backgroundColor,
      floatingActionButton: floatingActionButton,
      floatingActionButtonLocation: floatingActionButtonLocation,
      bottomNavigationBar: bottomNavigationBar,
      drawer: drawer,
      endDrawer: endDrawer,
      extendBody: extendBody,
      resizeToAvoidBottomInset: resizeToAvoidBottomInset,
    );
  }
}
