global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'temporal'
    metrics_path: /metrics
    static_configs:
      - targets: ['temporal:9090']

  - job_name: 'dapr'
    metrics_path: /metrics
    static_configs:
      - targets: ['user_manager:3500']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8100']
